import pandas as pd
from DB_SQL_SERVER import DB_SQL_Server
#%%
df = pd.read_excel('PRECIOS_2023.xlsx')

#%% ALMACENAMOS A UNA BAS DE DATOS
obj_database = DB_SQL_Server('10.1.12.46', 'Pruebas1')

obj_database.Connect_db()
sql_create = '''
DROP TABLE IF EXISTS preciosGLP
CREATE TABLE preciosGLP(
	ID int not null IDENTITY(1,1) PRIMARY KEY,
	ACTIVIDAD VARCHAR(200),
	REGISTRO_HIDROCARBUROS VARCHAR(200),
	RUC VARCHAR(200),
	RAZON_SOCIAL VARCHAR(200),
	DEPARTAMENTO VARCHAR(200),
	PROVINCIA VARCHAR(200),
	DISTRITO VARCHAR(200),
	DIRECCION VARCHAR(200),
	FECHA_REGISTRO DATETIME,
	PRODUCTO VARCHAR(200),
	TIPO_CLIENTE VARCHAR(200),
	MARCA VARCHAR(200),
	PRECIO_VENTA FLOAT,
	UNIDAD VARCHAR(50)
)
'''.strip()
columns = ['ACTIVIDAD','REGISTRO_HIDROCARBUROS','RUC','RAZON_SOCIAL',
           'DEPARTAMENTO','PROVINCIA','DISTRITO','DIRECCION','FECHA_REGISTRO',
           'PRODUCTO','TIPO_CLIENTE','MARCA','PRECIO_VENTA','UNIDAD']
obj_database.STORAGE_ROWS_db(sql_create,columns,df.values,'preciosGLP')
obj_database.Close_db()